---
title: "fmatch() performance"
output: html_document
vignette: >
  %\VignetteIndexEntry{fmatch() performance}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, setup}
library(tidyverse)
library(ggplot2)
library(microbenchmark)
library(ggtools)
library(fmatch)
```

```{r SAMPLE_SIZES}
SAMPLE_SIZES <- c(1, 3, 10, 30, 100, 300, 1e3, 3e3, 10e3, 30e3, 100e3)
```

```{r data}
strings <- readRDS(here::here("tests", "testthat", "data", "strings.Rds"))
patterns <- readRDS(here::here("tests", "testthat", "data", "patterns.Rds"))
```

```{r time_it}
time_it <- function (size = 1, times = 3) {
  sampled_strings <- sample(strings, size, replace = TRUE)
  microbenchmark(fmatch(sampled_strings, patterns), times = times)
}
```

```{r timings}
timings <- map(SAMPLE_SIZES, time_it)
```

```{r timing_data}
timing_data <-
  tibble(
    size = SAMPLE_SIZES,
    nanoseconds = map(timings, pluck, "time")) %>%
  tidyr::unchop(
    nanoseconds)
```

```{r ggplot-timing_data, width = 8, height = 10, out.width = 800, out.height = 1000}
timing_data %>%
  ggplot(aes(size, nanoseconds / 1e9, group = size)) +
  geom_point(alpha = I(0.5)) +
  scale_x_log10("sample size", limits = c(1, 1e7), expand = expansion(0, 1)) +
  scale_y_log10("time (seconds)", limits = c(1e-4, 1e3)) +
  annotate("point", shape = "+", x = 3e4, y = 3, color = "darkgreen", size = I(10)) +
  labs(
    title = "Scalability of fmatch::fmatch()",
    subtitle = str_c(
      "Points are timings via microbenchmark::microbenchmark().",
      "Needles are 12-character strings derived from RY2011 data (concatenations of `cat_id` and `SIC_id`).",
      "X axis (\"sample size\") is the number of needles.",
      "There are about 750 haystacks (derived from `Ingres::t0130`). Haystacks are also 12-character strings.",
      "The green cross is the target (~3 seconds to match 30k 12-char needles against 750 12-char haystacks)",
      sep = "\n"))
```